/**
 * GameON Tele - Data-Driven Game Catalog (Designed for 100+ Games)
 * Scalable Game Discovery, Category Classification, and Access Models.
 */

import { getGameArtworkUrl } from './gameArtwork';

export type GameAccessType = 'FREE' | 'COIN' | 'SUBSCRIPTION' | 'PURCHASE' | 'TRIAL';

export interface GameSubscriptionOptions {
  daily?: { enabled: boolean; priceETB: number };
  weekly?: { enabled: boolean; priceETB: number };
  monthly?: { enabled: boolean; priceETB: number };
}

export interface CatalogGame {
  gameId: string;
  gameName: string;
  titleAmharic: string;
  category: 'Action' | 'Arcade' | 'Puzzle' | 'Racing' | 'Sports' | 'Adventure' | 'Board' | 'Music' | 'Casual' | 'Strategy' | 'Other';
  genre: string;
  tagline: string;
  description: string;
  thumbnail: string;
  banner: string;
  accessType: GameAccessType;
  price?: number; // for ONE-TIME PURCHASE
  billingPeriod?: ('daily' | 'weekly' | 'monthly')[];
  isFeatured: boolean;
  isActive: boolean;
  isNew: boolean;
  isRecommended?: boolean;
  isFree: boolean;
  requiresCoins: boolean;
  coinCost: number;
  subscriptionOptions?: GameSubscriptionOptions;
  leaderboardEnabled: boolean;
  sortOrder: number;
  providerId?: string;
  providerName?: string;
  rating: number;
  playsCount: number;
  instructions: string[];
  controlsDescription: string;
  primaryColor: string;
  secondaryColor: string;
}

export const ALL_STANDARD_CATEGORIES = [
  'All Games',
  'Action',
  'Arcade',
  'Puzzle',
  'Racing',
  'Sports',
  'Adventure',
  'Board',
  'Music',
  'Casual',
  'Strategy',
  'Other',
] as const;

export const MANDATORY_CATALOG_ORDER = [
  'helix-jump',            // 1. Helix
  'emoji-iq',              // 2. Emoji
  'royal-water-sort',      // 3. Water Sort
  'archery-strike',        // 4. Pop Color
  'halloween-fruit-slice', // 5. Fruit Ninja
  'knife-madness',         // 6. Knife Hit
  'sorting-balls',         // 7. Sort
  'puzzle-block',          // 8. Block Puzzle
  'memory-match',          // 9. Memory
  'color-rush',            // 10. Color Quick
  'soccer-shooter',        // 11. Soccer Hit
  'button-soccer',         // 12. Button Soccer
  'moto-race',             // 13. Moto Race
  'sky-hopper',            // 14. Sky Hopper
  'solitaire',             // 15. Solitaire
  'emoji-sorting-ball',    // 16. Emoji Sort
  'hockey',                // 17. Hockey
  'fruit-fancy',           // 18. Fruit Fancy
  'picture-match',         // 19. Picture Match
  'candy-bomb',            // 20. Candy Bomblink Color
  'tap-rush',              // 21. Tap Rush
] as const;

export const INITIAL_GAME_CATALOG: CatalogGame[] = [
  {
    gameId: 'emoji-fun',
    gameName: 'EMOJI FUN',
    titleAmharic: 'ኢሞጂ ፈን',
    category: 'Puzzle',
    genre: 'Tournament Emoji Puzzle & Knowledge',
    tagline: 'Master 40 levels of emoji puzzles, combinations, sequences & tournament scoring!',
    description: 'The official EMOJI FUN tournament puzzle arena. Solve 15 unique emoji puzzle categories across 40 levels with dynamic skill-based scoring, combos, hints, lives, store, and competitive leaderboard.',
    thumbnail: getGameArtworkUrl('emoji-fun'),
    banner: getGameArtworkUrl('emoji-fun'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: false,
    isRecommended: false,
    isActive: false,
    isNew: false,
    leaderboardEnabled: false,
    sortOrder: 0,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.99,
    playsCount: 350000,
    primaryColor: '#ffb300',
    secondaryColor: '#f43f5e',
    instructions: [
      'Analyze the emoji presentation and answer before the countdown timer expires',
      'Answer quickly to earn up to +50% speed bonus points',
      'Chain consecutive correct answers to multiply tournament score up to 2.5x',
      'Use hints to eliminate wrong choices when stuck on tricky puzzles',
    ],
    controlsDescription: 'Tap the correct answer tile.',
  },
  {
    gameId: 'crazy-colors',
    gameName: 'Crazy Color',
    titleAmharic: 'ክሬዚ ከለር',
    category: 'Arcade',
    genre: 'Precision Color Match Physics',
    tagline: 'Bounce upwards, pass through matching neon obstacles, and conquer 40 levels!',
    description: 'The definitive 40-level Crazy Colors experience based on authentic color-matching physics. Tap to bounce against gravity, time passes through matching neon segments, collect stars, and become the Grandmaster!',
    thumbnail: getGameArtworkUrl('crazy-colors'),
    banner: getGameArtworkUrl('crazy-colors'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: false,
    isRecommended: false,
    isActive: false,
    isNew: false,
    leaderboardEnabled: false,
    sortOrder: 1,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.99,
    playsCount: 560000,
    primaryColor: '#FF008C',
    secondaryColor: '#00D9FF',
    instructions: [
      'Tap anywhere on the screen to bounce upwards against gravity',
      'Your ball can only pass through obstacle segments that match its current color',
      'Passing through Color Switcher orbs changes your ball color for upcoming obstacles',
    ],
    controlsDescription: 'Tap or click screen to jump. Spacebar supported on desktop.',
  },
  {
    gameId: 'fruit-slice',
    gameName: 'Fruit Ninja Classic',
    titleAmharic: 'ፍሩት ኒንጃ',
    category: 'Action',
    genre: '3D Katana Blade Slicing',
    tagline: 'Slice 3D fruits, trigger juicy combos, and master 40 Katana levels!',
    description: 'Experience exhilarating 3D Katana blade fruit slicing. Swipe through flying fruits, split juicy watermelons, kiwis, pineapples and coconuts, avoid dangerous bombs, and conquer 40 progressive stages.',
    thumbnail: getGameArtworkUrl('fruit-slice'),
    banner: getGameArtworkUrl('fruit-slice'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: false,
    isRecommended: false,
    isActive: false,
    isNew: false,
    leaderboardEnabled: false,
    sortOrder: 2,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.99,
    playsCount: 345000,
    primaryColor: '#e11d48',
    secondaryColor: '#f59e0b',
    instructions: [
      'Swipe or slide across the screen to slice incoming flying fruits',
      'Slice 2 or more fruits in a single swipe for combo multipliers',
      'Avoid slicing black bombs, and do not let fruits drop uncut',
    ],
    controlsDescription: 'Swipe or drag with finger on touchscreens, or drag mouse on desktop.',
  },
  {
    gameId: 'juicy-match',
    gameName: 'Candy Juicy',
    titleAmharic: 'ኬንዲ ጁሲ',
    category: 'Puzzle',
    genre: '3D Tropical Match-3',
    tagline: 'Match glossy 3D tropical fruits, trigger juice cascades, and conquer 40 island levels!',
    description: 'A vibrant and juicy Match-3 puzzle adventure. Swap 3D strawberries, blueberries, kiwi slices, bananas, and grapes to shatter crates, uncover treasure chests, and unleash Rainbow Bomb combos across 40 challenging tropical levels.',
    thumbnail: getGameArtworkUrl('juicy-match'),
    banner: getGameArtworkUrl('juicy-match'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: false,
    isRecommended: false,
    isActive: false,
    isNew: false,
    leaderboardEnabled: false,
    sortOrder: 3,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.99,
    playsCount: 420000,
    primaryColor: '#f59e0b',
    secondaryColor: '#0284c7',
    instructions: [
      'Swipe or tap adjacent fruits to create rows or columns of 3 matching fruits',
      'Match 4 fruits to create Striped Fruits that blast entire rows or columns',
      'Match 5 fruits in a line to form the Rainbow Super Fruit that clears all fruits of one color',
    ],
    controlsDescription: 'Swipe or tap adjacent fruits to swap. Tap boosters to activate.',
  },
  {
    gameId: 'bubble-shooter',
    gameName: 'Bubble Shooter',
    titleAmharic: 'ባብል ሹተር',
    category: 'Puzzle',
    genre: 'Hexagonal Bubble Match',
    tagline: 'Aim, reflect wall bank shots, and pop dense glossy bubble clusters!',
    description: 'The tournament edition of the classic Bubble Shooter. Aim the precision dotted laser guide, calculate tactical wall bank shots, trigger satisfying cluster drop cascades, and conquer 40 progressive stages.',
    thumbnail: getGameArtworkUrl('bubble-shooter'),
    banner: getGameArtworkUrl('bubble-shooter'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: false,
    isRecommended: false,
    isActive: false,
    isNew: false,
    leaderboardEnabled: false,
    sortOrder: 4,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.98,
    playsCount: 230000,
    primaryColor: '#1788E8',
    secondaryColor: '#071626',
    instructions: [
      'Touch and drag in the lower area to aim the dotted trajectory guide',
      'Bounce shots off side walls to reach concealed high-value color clusters',
      'Connect 3 or more matching bubbles to pop them and drop unsupported clusters',
    ],
    controlsDescription: 'Drag to aim, release to shoot. Tap swap button to exchange next bubble.',
  },
  {
    gameId: 'helix-jump',
    gameName: 'Helix',
    titleAmharic: 'ሄሊክስ',
    category: 'Arcade',
    genre: '3D Cylinder Tower Drop Arcade',
    tagline: 'Rotate the central tower, drop through gaps, and conquer 40 levels!',
    description: 'The definitive 40-level 3D Helix Jump experience. Swipe horizontally to rotate the cylindrical tower, guide the bouncing ball through open gaps, land on safe sectors, and trigger fiery multi-level combo smashes.',
    thumbnail: getGameArtworkUrl('helix-jump'),
    banner: getGameArtworkUrl('helix-jump'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isActive: true,
    isNew: true,
    leaderboardEnabled: true,
    sortOrder: 5,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.99,
    playsCount: 620000,
    primaryColor: '#0284c7',
    secondaryColor: '#f59e0b',
    instructions: [
      'Swipe or drag left and right on the screen to rotate the central helix tower',
      'Align open gaps directly underneath the bouncing ball to descend through the rings',
      'Avoid red or orange danger platform sectors that shatter the ball',
    ],
    controlsDescription: 'Swipe left/right to rotate tower. Drag finger or mouse horizontally.',
  },
  {
    gameId: 'pop-piano',
    gameName: 'Pop Piano',
    titleAmharic: 'ፖፕ ፒያኖ',
    category: 'Music',
    genre: 'Rhythm Piano Beat Tiles',
    tagline: 'Tap falling glowing keys to chart-topping melodies and rhythms!',
    description: 'Fast rhythm piano tile gameplay featuring popular songs, acoustic chords, and global hits. Tap descending piano tiles in sync with the beat to achieve perfect harmony.',
    thumbnail: getGameArtworkUrl('pop-piano'),
    banner: getGameArtworkUrl('pop-piano'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: false,
    isRecommended: false,
    isActive: false,
    isNew: false,
    leaderboardEnabled: false,
    sortOrder: 6,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.9,
    playsCount: 187400,
    primaryColor: '#8b5cf6',
    secondaryColor: '#70C922',
    instructions: [
      'Tap the descending piano tiles exactly as they hit the rhythm baseline bar',
      'Hold down long note tiles for sustained chord points and acoustic vibrato',
      'Do not tap empty spaces or let any piano note pass the baseline without tapping',
    ],
    controlsDescription: 'Tap keys on screen or use keyboard keys [D] [F] [J] [K].',
  },
  {
    gameId: 'world-legends',
    gameName: 'Word Legend',
    titleAmharic: 'ዎርድ ሌጀንድ',
    category: 'Puzzle',
    genre: 'Civilization & Mythology Trivia Puzzle',
    tagline: 'Journey through world history, mythology, ancient civilizations, and lore!',
    description: 'An immersive knowledge and trivia adventure. Answer intriguing questions on world civilizations, ancient mythology, Ethiopian imperial heritage, and legendary world events.',
    thumbnail: getGameArtworkUrl('world-legends'),
    banner: getGameArtworkUrl('world-legends'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: false,
    isRecommended: false,
    isActive: false,
    isNew: false,
    leaderboardEnabled: false,
    sortOrder: 7,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.9,
    playsCount: 189000,
    primaryColor: '#f59e0b',
    secondaryColor: '#05234A',
    instructions: [
      'Answer 10 rapid multiple-choice legend questions before the 15-second timer runs out',
      'Score bonus speed points by answering accurately within the first 3 seconds',
      'Use 50:50 and Clue lifelines when facing complex historical questions',
    ],
    controlsDescription: 'Tap the correct historical answer card.',
  },
  {
    gameId: 'candy-blast',
    gameName: 'Candy Crush',
    titleAmharic: 'ኬንዲ ክራሽ',
    category: 'Puzzle',
    genre: 'Match-3 Confectionery Puzzle',
    tagline: 'Match vibrant honey candies, trigger sweet sugar blasts and combos!',
    description: 'A delightful confectionery match-3 puzzle. Swap and connect 3 or more delicious honey candies to trigger colorful cascades, sweet sugar blasts, and massive combo multipliers.',
    thumbnail: getGameArtworkUrl('candy-blast'),
    banner: getGameArtworkUrl('candy-blast'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: false,
    isRecommended: false,
    isActive: false,
    isNew: false,
    leaderboardEnabled: false,
    sortOrder: 8,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.9,
    playsCount: 245000,
    primaryColor: '#e11d48',
    secondaryColor: '#70C922',
    instructions: [
      'Swap adjacent candies to create horizontal or vertical rows of 3 matching colors',
      'Match 4 candies to create explosive Striped Candies that clear entire rows',
      'Combine 5 candies to form a Rainbow Honey Bomb that blasts all candies of the same color',
    ],
    controlsDescription: 'Tap and swipe candies to swap positions.',
  },
  {
    gameId: 'emoji-iq',
    gameName: 'Emoji',
    titleAmharic: 'ኢሞጂ',
    category: 'Puzzle',
    genre: 'Tournament Emoji & Number Calculation Challenge',
    tagline: 'Master 40 stages of emoji equations, logical calculations & tournament scoring!',
    description: 'The official EMOJI tournament arena. Solve 12 unique emoji equation puzzle categories across 40 progressive stages with multi-step calculations, order of operations, changed quantities, visual differences, combos, hints, lives, store, and competitive leaderboard.',
    thumbnail: getGameArtworkUrl('emoji-iq'),
    banner: getGameArtworkUrl('emoji-iq'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isActive: true,
    isNew: true,
    leaderboardEnabled: true,
    sortOrder: 9,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.99,
    playsCount: 380000,
    primaryColor: '#6C5CE7',
    secondaryColor: '#00B8D9',
    instructions: [
      'Deduce the numerical values of emojis from the clue equations',
      'Mind the order of operations (PEMDAS): calculate multiplication and division first',
      'Watch for changes in emoji quantity (pairs vs singles) and visual differences',
      'Answer quickly without hints to claim +30% speed bonuses and ⭐ PERFECT! badges',
    ],
    controlsDescription: 'Tap the correct numerical answer tile.',
  },
  {
    gameId: 'royal-water-sort',
    gameName: 'Water Sort',
    titleAmharic: 'ወተር ሶርት',
    category: 'Puzzle',
    genre: '3D Royal Glass Water Sort Puzzle',
    tagline: 'Pour glossy liquid into 3D glass bottles, unlock golden corks, and conquer 40 Championship levels!',
    description: 'The premier 3D glass liquid sorting puzzle experience. Select crystal vials, pour vibrant liquid layers, plan complex multi-color transfers, use Undo, Shuffle & Extra Tube boosters, and conquer 40 Very Difficult royal championship levels.',
    thumbnail: getGameArtworkUrl('royal-water-sort'),
    banner: getGameArtworkUrl('royal-water-sort'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isActive: true,
    isNew: true,
    leaderboardEnabled: true,
    sortOrder: 10,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.99,
    playsCount: 310000,
    primaryColor: '#38BDF8',
    secondaryColor: '#FFD54F',
    instructions: [
      'Tap a glass bottle to lift and select it',
      'Tap another bottle to tilt and pour its top matching liquid group',
      'Fill each bottle with a single pure color to lock its golden cork and complete the level',
    ],
    controlsDescription: 'Tap source bottle, then tap destination bottle to pour.',
  },
  {
    gameId: 'archery-strike',
    gameName: 'Pop Color',
    titleAmharic: 'ፖፕ ከለር',
    category: 'Arcade',
    genre: 'Reflex Balloon Pop Arcade',
    tagline: 'Tap and pop falling colored balloons before they reach the bottom!',
    description: 'Fast-paced reflex game. Tap and pop vibrant falling colored balloons while testing your speed, rhythm, and accuracy before any balloons slip past.',
    thumbnail: getGameArtworkUrl('archery-strike'),
    banner: getGameArtworkUrl('archery-strike'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: false,
    isRecommended: false,
    isActive: true,
    isNew: false,
    leaderboardEnabled: true,
    sortOrder: 11,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.9,
    playsCount: 168000,
    primaryColor: '#EC4899',
    secondaryColor: '#3B82F6',
    instructions: [
      'Tap or click directly on each falling colored balloon to pop it instantly',
      'Do not tap empty background space or decorative borders',
      'Prevent balloons from escaping past the bottom to preserve your hearts',
    ],
    controlsDescription: 'Tap or click falling colored balloons to pop.',
  },
  {
    gameId: 'halloween-fruit-slice',
    gameName: 'Fruit Ninja',
    titleAmharic: 'ፍሩት ኒንጃ',
    category: 'Action',
    genre: 'Spooky Monster Fruit Slicing',
    tagline: 'Slice spooky monster fruits, dodge flying bombs, and conquer 40 very difficult levels!',
    description: 'A haunted twist on classic blade slicing! Swipe across flying monster fruits, carve juicy jack-o-lantern pumpkins, trigger multi-slice combos, and conquer 40 very difficult progressive levels.',
    thumbnail: getGameArtworkUrl('halloween-fruit-slice'),
    banner: getGameArtworkUrl('halloween-fruit-slice'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isActive: true,
    isNew: true,
    leaderboardEnabled: true,
    sortOrder: 12,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.98,
    playsCount: 185000,
    primaryColor: '#FF6B00',
    secondaryColor: '#00E5FF',
    instructions: [
      'Swipe finger or drag mouse across flying monster fruits to slice them',
      'Never slice danger bombs or your run ends immediately',
      'Slice multiple monster fruits in a single swipe to trigger high-scoring combos',
      'Level 1 is calibrated to be very difficult - maintain high focus!',
    ],
    controlsDescription: 'Swipe finger or click & drag mouse to slice.',
  },
  {
    gameId: 'hill-rider',
    gameName: 'Hill Climb',
    titleAmharic: 'ሂል ክላይምብ',
    category: 'Racing',
    genre: 'Highland Physics Driving',
    tagline: 'Conquer steep highland ridges and rugged mountain terrains!',
    description: 'Physics-based 2D hill climbing driving game. Control acceleration and vehicle pitch balance over steep highland hills, rocky gorges, and suspension bridges to reach the summit.',
    thumbnail: getGameArtworkUrl('hill-rider'),
    banner: getGameArtworkUrl('hill-rider'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: false,
    isRecommended: false,
    isActive: false,
    isNew: false,
    leaderboardEnabled: false,
    sortOrder: 13,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.7,
    playsCount: 119800,
    primaryColor: '#0B3B70',
    secondaryColor: '#70C922',
    instructions: [
      'Hold Gas (Right) to accelerate uphill and release on steep drops to maintain traction',
      'Use Brake / Tilt (Left) to slow down and stabilize buggy balance mid-air',
      'Collect fuel jerrycans along the track before your vehicle engine runs dry',
    ],
    controlsDescription: 'Tap/hold Gas (Right) & Brake (Left) on screen, or use Arrow keys.',
  },
  {
    gameId: 'knife-madness',
    gameName: 'Knife Hit',
    titleAmharic: 'ናይፍ ሂት',
    category: 'Arcade',
    genre: '3D Precision Target Throwing',
    tagline: 'Throw steel knives, slice juicy apples, and shatter rotating 3D targets!',
    description: 'The ultimate test of precision timing and reflexes. Tap to throw steel knives into rotating 3D targets, slice apples for bonus points, avoid hitting existing blades, and shatter targets across 40 stages.',
    thumbnail: getGameArtworkUrl('knife-madness'),
    banner: getGameArtworkUrl('knife-madness'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: false,
    isRecommended: true,
    isActive: true,
    isNew: true,
    leaderboardEnabled: true,
    sortOrder: 14,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.99,
    playsCount: 385000,
    primaryColor: '#0284c7',
    secondaryColor: '#f59e0b',
    instructions: [
      'Tap the screen to launch a knife straight toward the rotating 3D target',
      'Time your throws carefully into open gaps to embed the required number of knives',
      'Avoid striking any pre-embedded knives or previously thrown blades',
    ],
    controlsDescription: 'Tap or click anywhere on screen to throw knife.',
  },
  {
    gameId: 'sorting-balls',
    gameName: 'Sort',
    titleAmharic: 'ሶርት',
    category: 'Puzzle',
    genre: '3D Color Sorting Puzzle',
    tagline: 'Sort vibrant glossy 3D spheres into glass cylinders across 40 mind-bending levels!',
    description: 'A beautifully relaxing and cerebral 3D color sorting puzzle. Strategically transfer colored spheres between glass cylinders until each tube contains exclusively identical colors.',
    thumbnail: getGameArtworkUrl('sorting-balls'),
    banner: getGameArtworkUrl('sorting-balls'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: false,
    isRecommended: true,
    isActive: true,
    isNew: false,
    leaderboardEnabled: true,
    sortOrder: 15,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.99,
    playsCount: 215000,
    primaryColor: '#FF8A00',
    secondaryColor: '#171B26',
    instructions: [
      'Tap any tube to select its top ball, then tap another valid tube to transfer it',
      'A ball can only be placed into an empty tube or on top of a matching color',
      'Sort all balls of each color into their dedicated tubes to solve the puzzle',
    ],
    controlsDescription: 'Tap source tube to lift ball, tap destination tube to drop.',
  },
  {
    gameId: 'puzzle-block',
    gameName: 'Block Puzzle',
    titleAmharic: 'ብሎክ ፓዝል',
    category: 'Puzzle',
    genre: '10x10 Wooden Block Puzzle',
    tagline: 'Place polyomino blocks on the 10x10 wooden board and clear full rows and columns!',
    description: 'The definitive 10x10 wooden block puzzle experience. Features 40 progressive championship levels, real drag & drop with touch-elevation offset, wood/ice/stone blockers, bomb blocks, and multi-line combo feedback.',
    thumbnail: getGameArtworkUrl('puzzle-block'),
    banner: getGameArtworkUrl('puzzle-block'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isActive: true,
    isNew: true,
    leaderboardEnabled: true,
    sortOrder: 16,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.99,
    playsCount: 520000,
    primaryColor: '#8a3f20',
    secondaryColor: '#f59e0b',
    instructions: [
      'Touch and drag block shapes from the bottom 3-piece tray onto the 10x10 board',
      'Fill complete 10-cell horizontal rows or vertical columns to collapse them',
      'Clear multiple lines simultaneously to trigger massive combo multipliers',
    ],
    controlsDescription: 'Touch and drag pieces onto the 10x10 board. Release over valid cells to place.',
  },
  {
    gameId: 'memory-match',
    gameName: 'Memory',
    titleAmharic: 'ሜሞሪ',
    category: 'Puzzle',
    genre: '3D Memory Card Pair Matching',
    tagline: 'Test your photographic memory and uncover legendary matching relics!',
    description: 'A premium, high-stakes memory matching experience. Flip beautifully beveled 3D cards, remember mysterious symbols and ancient artifacts, and uncover matching pairs across challenging stages.',
    thumbnail: getGameArtworkUrl('memory-match'),
    banner: getGameArtworkUrl('memory-match'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: false,
    isRecommended: false,
    isActive: true,
    isNew: false,
    leaderboardEnabled: true,
    sortOrder: 17,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.95,
    playsCount: 142000,
    primaryColor: '#0B3B70',
    secondaryColor: '#8BCB3D',
    instructions: [
      'Tap face-down cards to reveal their hidden ancient symbol',
      'Find and match identical pairs to clear the board before time runs out',
      'Build consecutive match streaks to multiply your score and earn 3 gold stars',
    ],
    controlsDescription: 'Tap or click any card to flip.',
  },
  {
    gameId: 'color-rush',
    gameName: 'Color Quick',
    titleAmharic: 'ከለር ኩዊክ',
    category: 'Arcade',
    genre: 'Reflex Speed Timing Arcade',
    tagline: 'Test your lightning-fast reflex timing against the chromatic rush!',
    description: 'High-speed reflex reaction test. Match incoming chromatic neon pulses and rotating color gates before the countdown runs out. Speed increases with every successful combo!',
    thumbnail: getGameArtworkUrl('color-rush'),
    banner: getGameArtworkUrl('color-rush'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: false,
    isRecommended: true,
    isActive: true,
    isNew: false,
    leaderboardEnabled: true,
    sortOrder: 18,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.8,
    playsCount: 132600,
    primaryColor: '#70C922',
    secondaryColor: '#0B3B70',
    instructions: [
      'Watch the target color flash on screen and tap the matching color paddle immediately',
      'Keep your reaction streak alive to trigger the 3x Multiplier Fever mode',
      'Avoid incorrect taps which instantly break your combo streak and cost a life',
    ],
    controlsDescription: 'Tap color buttons or press Arrow keys in rapid sequence.',
  },
  {
    gameId: 'soccer-shooter',
    gameName: 'Soccer Hit',
    titleAmharic: 'ሶከር ሂት',
    category: 'Sports',
    genre: 'Stadium Soccer Bubble Match',
    tagline: 'Kick 3D national soccer balls, execute wall bank shots, and clear 40 World Cup levels!',
    description: 'The championship edition of Soccer Hit. Aim the precision dotted trajectory guide from the penalty spot, bank shots off stadium walls, trigger massive goalmouth cluster drops (+250 PTS), and manage penalty fouls.',
    thumbnail: getGameArtworkUrl('soccer-shooter'),
    banner: getGameArtworkUrl('soccer-shooter'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: false,
    isRecommended: true,
    isActive: true,
    isNew: true,
    leaderboardEnabled: true,
    sortOrder: 19,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.99,
    playsCount: 275000,
    primaryColor: '#009739',
    secondaryColor: '#061325',
    instructions: [
      'Touch and drag in the stadium field to aim the precision dotted trajectory laser',
      'Bounce kicks off stadium walls to reach upper root soccer balls and trigger falling cascades',
      'Match 3 or more soccer balls to pop them with crowd celebration',
    ],
    controlsDescription: 'Touch/drag to aim, release to kick. Tap SWAP button to change upcoming ball.',
  },
  {
    gameId: 'dama',
    gameName: 'Dama',
    titleAmharic: 'ዳማ',
    category: 'Board',
    genre: '3D Ethiopian Draughts Strategy',
    tagline: 'Master the 3D championship draughts board against intelligent tactical AI!',
    description: 'Single-player 3D Draughts (Dama) against an advanced computer opponent. Experience physical wooden pieces, realistic board depth, mandatory captures, multi-jumps, and king crowning across progressive challenges.',
    thumbnail: getGameArtworkUrl('dama'),
    banner: getGameArtworkUrl('dama'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isActive: true,
    isNew: false,
    leaderboardEnabled: true,
    sortOrder: 20,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.98,
    playsCount: 156000,
    primaryColor: '#b45309',
    secondaryColor: '#1c1917',
    instructions: [
      'Tap your white pieces to reveal legal diagonal moves and mandatory capture paths',
      'Jumps and chain captures are strictly mandatory when available on the board',
      'Reach the opponent back rank to crown your piece into a powerful King',
    ],
    controlsDescription: 'Tap piece to select, then tap highlighted square to move.',
  },
  {
    gameId: 'button-soccer',
    gameName: 'Button Soccer',
    titleAmharic: 'የአዝራር እግር ኳስ',
    category: 'Sports',
    genre: '2026 World Tour Table Soccer',
    tagline: 'Drag back to aim & power, execute bank shots, and conquer 40 very difficult Championship levels!',
    description: 'The authentic 2026 World Tour button soccer tournament. Choose your nation, drag back from your 3D team discs to aim & power, score against very difficult AI opponents, and conquer 40 championship levels with pass-and-play 2-player mode.',
    thumbnail: getGameArtworkUrl('button-soccer'),
    banner: getGameArtworkUrl('button-soccer'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isActive: true,
    isNew: true,
    leaderboardEnabled: true,
    sortOrder: 21,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.99,
    playsCount: 210000,
    primaryColor: '#009C3B',
    secondaryColor: '#FFD54F',
    instructions: [
      'Touch and drag backward from your team disc to aim and set shot power',
      'Release to strike the soccer ball towards the opponent goal',
      'First team to reach the target goals or highest score at full time wins',
    ],
    controlsDescription: 'Touch and drag backward from your disc to aim & set power, release to shoot.',
  },
  {
    gameId: 'soccer-ping-pong',
    gameName: 'Soccer Ping Pong',
    titleAmharic: 'ሶከር ፒንግ ፖንግ',
    category: 'Sports',
    genre: '3D Soccer Table Tennis Arcade',
    tagline: 'Master professional 3D soccer table tennis across 20 stadium levels!',
    description: 'Control a high-velocity 3D soccer ball in fast-paced table tennis rallies against tactical AI opponents. Execute precision volleys, curve spins, power smashes, and obstacle rebounds across 6 progressive stadiums.',
    thumbnail: getGameArtworkUrl('soccer-ping-pong'),
    banner: getGameArtworkUrl('soccer-ping-pong'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isActive: true,
    isNew: true,
    leaderboardEnabled: true,
    sortOrder: 22,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.99,
    playsCount: 198000,
    primaryColor: '#1688C9',
    secondaryColor: '#8BCB3D',
    instructions: [
      'Slide your striker left and right to intercept the incoming soccer ball',
      'Time returns within the glowing green Sweet-Spot zone for power shots and combo multipliers',
      'Maintain continuous rallies without letting the ball pass your baseline',
    ],
    controlsDescription: 'Touch and drag striker horizontally, or use mouse / arrow keys.',
  },
  {
    gameId: 'moto-race',
    gameName: 'Moto Race',
    titleAmharic: 'ሞተር ሬስ',
    category: 'Racing',
    genre: '3D First-Person Highway Racing',
    tagline: 'First-person high-speed highway traffic racing across 40 progressive city levels!',
    description: 'Experience adrenaline-pumping 3D first-person motorcycle highway racing. Grip the handlebars, lean into turns, weave through high-density urban traffic, execute close near-miss overtakes, and conquer 40 progressive stages.',
    thumbnail: getGameArtworkUrl('moto-race'),
    banner: getGameArtworkUrl('moto-race'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isActive: true,
    isNew: true,
    leaderboardEnabled: true,
    sortOrder: 23,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.99,
    playsCount: 312000,
    primaryColor: '#0284c7',
    secondaryColor: '#8BCB3D',
    instructions: [
      'Steer left and right using screen arrow buttons or Left/Right arrow keys',
      'Hold GAS to accelerate up to 148 km/h and maintain high-speed streaks',
      'Execute close near-miss overtakes within inches of traffic for combo bonuses',
    ],
    controlsDescription: 'Touch steer/gas/brake buttons or use keyboard Arrow keys.',
  },
  {
    gameId: 'solitaire',
    gameName: 'Solitaire',
    titleAmharic: 'ሶሊቴር',
    category: 'Puzzle',
    genre: 'Classic Klondike Solitaire',
    tagline: 'Master authentic 52-card Klondike Solitaire across 40 championship levels!',
    description: 'The definitive Klondike Solitaire experience. Features Draw 1 and Draw 3 modes, authentic playing card artwork, deep emerald felt table acoustics, 40 progressive levels, daily challenge deals, unlimited undo, smart hints, and auto-complete.',
    thumbnail: getGameArtworkUrl('solitaire'),
    banner: getGameArtworkUrl('solitaire'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isActive: true,
    isNew: false,
    leaderboardEnabled: true,
    sortOrder: 24,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.99,
    playsCount: 485000,
    primaryColor: '#007a40',
    secondaryColor: '#ffd54f',
    instructions: [
      'Stack cards in descending order (King down to Ace) in alternating red and black suits',
      'Build the 4 foundation piles from Ace to King by suit',
      'Draw from the stock pile to discover new strategic cards',
    ],
    controlsDescription: 'Tap any card to auto-move, or drag and place freely. Tap stock to draw.',
  },
  {
    gameId: 'emoji-sorting-ball',
    gameName: 'Emoji Sort',
    titleAmharic: 'ኢሞጂ ሶርት',
    category: 'Puzzle',
    genre: '3D Emoji Sorting Tournament Puzzle',
    tagline: 'Sort stylized 3D emoji vinyl spheres into color-coded crystal tubes across 40 levels!',
    description: 'The premier 3D Emoji Sorting tournament challenge. Transfer identical emoji spheres between vibrant tubes, utilize sequential multi-ball transfers, manage undos, hints, and buffer tubes, and maximize your tournament par efficiency.',
    thumbnail: getGameArtworkUrl('emoji-sorting-ball'),
    banner: getGameArtworkUrl('emoji-sorting-ball'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isActive: true,
    isNew: true,
    leaderboardEnabled: true,
    sortOrder: 25,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.99,
    playsCount: 280000,
    primaryColor: '#8B5CF6',
    secondaryColor: '#F472B6',
    instructions: [
      'Tap any tube to lift top emoji ball(s), then tap destination tube with matching emoji or empty space',
      'Contiguous matching emojis transfer together in a coordinated sequential wave',
      'Finish each puzzle in minimum moves to earn 3 stars and tournament Par bonus score',
      'Use Undo (-50 PTS), Hints (-150 PTS), or Add Extra Tube (-250 PTS) when stuck',
    ],
    controlsDescription: 'Tap source tube to select emoji, tap destination tube to transfer.',
  },
  {
    gameId: 'sky-hopper',
    gameName: 'Sky Hopper',
    titleAmharic: 'ስካይ ሆፐር',
    category: 'Arcade',
    genre: 'Precision Flight Arcade',
    tagline: 'Flap, dodge green pipes, collect gold coins, and conquer all 40 levels!',
    description: 'Fly through challenging obstacles in this thrilling arcade classic. Master smooth flight physics, collect golden coins, and advance through 40 deterministic levels to become the Sky Hopper Grandmaster.',
    thumbnail: getGameArtworkUrl('sky-hopper'),
    banner: getGameArtworkUrl('sky-hopper'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isActive: true,
    isNew: true,
    leaderboardEnabled: true,
    sortOrder: 26,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.95,
    playsCount: 154000,
    primaryColor: '#38BDF8',
    secondaryColor: '#73BF2E',
    instructions: [
      'Tap, click, or press Spacebar to flap upward',
      'Navigate safely between the upper and lower green pipes',
      'Collect floating golden coins along your flight path',
      'Pass the required number of pipes in each level to advance to the next level',
    ],
    controlsDescription: 'Tap anywhere on screen or press Spacebar / Up Arrow to flap upward.',
  },
  {
    gameId: 'hockey',
    gameName: 'Hockey',
    titleAmharic: 'ሆኪ',
    category: 'Sports',
    genre: 'Neon Air Hockey Tournament',
    tagline: 'Defend your goal, strike the glowing puck, and conquer all 40 Very Hard stages!',
    description: 'High-octane neon air hockey tournament featuring 40 deterministic stages against competitive CPU opponents on permanent Very Hard difficulty.',
    thumbnail: getGameArtworkUrl('hockey'),
    banner: getGameArtworkUrl('hockey'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isActive: true,
    isNew: true,
    leaderboardEnabled: true,
    sortOrder: 27,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.96,
    playsCount: 168000,
    primaryColor: '#06B6D4',
    secondaryColor: '#EF4444',
    instructions: [
      'Drag your glowing mallet using touch or mouse within your defensive half',
      'Strike the glowing puck past the CPU opponent and into their goal',
      'Block oncoming ricochet shots and defend your goal net',
      'Reach the target goal score to clear each stage and unlock the next challenge',
    ],
    controlsDescription: 'Touch drag or mouse drag your circular mallet within your half of the table.',
  },
  {
    gameId: 'catch-up',
    gameName: 'Catch Up',
    titleAmharic: 'ኬች አፕ',
    category: 'Arcade',
    genre: 'Highway Speed Runner Tournament',
    tagline: 'Steer the speeding ball, dodge barricades, collect diamonds, and conquer 40 Very Hard stages!',
    description: 'Adrenaline-fueled 3D perspective highway speed runner. Steer the rolling ball through dense road barricades, hazard ramps, and brick pillars across 40 deterministic stages on permanent Very Hard difficulty.',
    thumbnail: getGameArtworkUrl('catch-up'),
    banner: getGameArtworkUrl('catch-up'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isActive: true,
    isNew: true,
    leaderboardEnabled: true,
    sortOrder: 28,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.98,
    playsCount: 215000,
    primaryColor: '#0284C7',
    secondaryColor: '#EF4444',
    instructions: [
      'Drag left or right using touch or mouse to steer the speeding ball',
      'Pass between red/white construction barricades, brick pillars, and hazard ramps',
      'Collect emerald diamonds along the highway to boost your score',
      'Survive the distance target to conquer each stage and unlock the next challenge',
    ],
    controlsDescription: 'Touch drag or mouse drag horizontally to steer the ball. Desktop: Left/Right arrows or A/D keys.',
  },
  {
    gameId: 'fruit-fancy',
    gameName: 'Fruit Fancy',
    titleAmharic: 'ፍሩት ፋንሲ',
    category: 'Puzzle',
    genre: 'Orchard Match-3 Puzzle Tournament',
    tagline: 'Swap delicious fruits, blast wooden tree stumps, break ice, and conquer 40 challenging levels!',
    description: 'Vibrant and challenging match-3 puzzle tournament set in a sunny fruit garden. Swap and match strawberries, blueberries, watermelons, and lemons. Clear tree stumps, ice, and crates across 40 handcrafted levels on progressive difficulty.',
    thumbnail: getGameArtworkUrl('fruit-fancy'),
    banner: getGameArtworkUrl('fruit-fancy'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isActive: true,
    isNew: true,
    leaderboardEnabled: true,
    sortOrder: 29,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.98,
    playsCount: 248000,
    primaryColor: '#16A34A',
    secondaryColor: '#EAB308',
    instructions: [
      'Swap adjacent fruits horizontally or vertically to create lines of 3 or more matching fruits',
      'Create 4-matches to produce line-clearing Arrow Fruits, and 5-matches for Rainbow Pinwheels',
      'Match adjacent fruits to break wooden tree stumps, crates, and melt ice blocks',
      'Fulfill all level objectives within the move limit to clear the stage and unlock the next challenge',
    ],
    controlsDescription: 'Touch drag or click adjacent fruits to swap. Mouse or touch controls fully supported.',
  },
  {
    gameId: 'picture-match',
    gameName: 'Picture Match',
    titleAmharic: 'የስዕል ማዛመጃ',
    category: 'Puzzle',
    genre: 'Memory / Tournament Puzzle',
    tagline: 'High-Stakes 40-Stage Picture Memory Tournament',
    description: 'High-octane tournament memory challenge. Memorize revealed cards in seconds, find matching pictures under severe tournament timers, and conquer all 40 demanding stages.',
    thumbnail: getGameArtworkUrl('picture-match'),
    banner: getGameArtworkUrl('picture-match'),
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isActive: true,
    isNew: true,
    leaderboardEnabled: true,
    sortOrder: 30,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.96,
    playsCount: 195000,
    primaryColor: '#00897B',
    secondaryColor: '#004D40',
    instructions: [
      'Memorize all card pictures during the countdown reveal window before cards turn face-down',
      'Tap any two cards to reveal them and match identical pictures',
      'Earn +5 bonus seconds added to your tournament timer for every pair matched',
      'Complete all pairs before the timer expires to unlock the next tournament stage',
    ],
    controlsDescription: 'Tap or click cards to flip and match pairs. 100% touch and mouse supported.',
  },
  {
    gameId: 'candy-bomb',
    gameName: 'Candy Bomblink Color',
    titleAmharic: 'ከረሜላ ቦምብ',
    category: 'Puzzle',
    genre: 'Tournament Match-3 & Candy Blast',
    tagline: 'Conquer 40 tournament match-3 challenges, explosive candy bombs and rainbow combos!',
    description: 'Experience high-stakes match-3 tournament gameplay across 40 hand-crafted stages. Match delicious glossy candies, trigger horizontal and vertical striped blasts, wrapped candy bomb detonations, and dazzling rainbow chocolate sprinkle color bombs to achieve high-score mastery under tight move limits.',
    thumbnail: 'https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?w=600&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?w=1200&auto=format&fit=crop&q=80',
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isNew: true,
    isActive: true,
    leaderboardEnabled: true,
    sortOrder: 31,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.98,
    playsCount: 220000,
    primaryColor: '#0284C7',
    secondaryColor: '#F59E0B',
    instructions: [
      'Swap adjacent candies horizontally or vertically to match 3 or more of the same color',
      'Match 4 in a line to forge a Striped Candy that clears an entire row or column with light beams',
      'Match 5 in T or L shape to forge a Wrapped Candy Bomb that detonates a 3x3 blast area',
      'Match 5 in a row to forge a Rainbow Chocolate Sprinkle Ball that clears all candies of any color you swap it with',
      'Combine special candies together for devastating screen-clearing combos',
      'Reach target color counts before running out of moves to advance through 40 tournament levels',
    ],
    controlsDescription: 'Tap or swipe adjacent candies to swap. Tap boosters to clear obstacles. 100% mobile touch & desktop mouse friendly.',
  },
  {
    gameId: 'link-color',
    gameName: 'LINK COLOR',
    titleAmharic: 'የቀለም ማገናኛ',
    category: 'Puzzle',
    genre: 'Tournament Color Link & Connect',
    tagline: 'Connect adjacent glossy color orbs, trigger vibrant paint splatters and master 40 tournament stages!',
    description: 'A tournament puzzle challenge built for elite spatial memory and chain matching. Drag across 3 or more adjacent same-color orbs to forge glowing links, burst juicy paint splatters, unleash devastating rainbow bombs, and complete high-difficulty color collection targets across 40 stages.',
    thumbnail: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=600&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=1200&auto=format&fit=crop&q=80',
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: false,
    isRecommended: false,
    isNew: false,
    isActive: false,
    leaderboardEnabled: false,
    sortOrder: 32,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.97,
    playsCount: 185000,
    primaryColor: '#0284C7',
    secondaryColor: '#10B981',
    instructions: [
      'Drag your finger or mouse across 3 or more adjacent balls of the same color to link them',
      'Trace your path backwards to undo or change your link sequence before releasing',
      'Release to trigger vibrant paint splatters, collecting the matched color toward your level targets',
      'Chain 6 or more balls together to forge a Rainbow Bomb that obliterates entire colors',
      'Complete all required color quotas within the allotted moves to unlock the next tournament level',
    ],
    controlsDescription: 'Click or touch and drag across adjacent matching colors to link. Release to pop. Boosters tap to activate.',
  },
  {
    gameId: 'tap-rush',
    gameName: 'Tap Rush',
    titleAmharic: 'ፈጣን ንክኪ',
    category: 'Arcade',
    genre: 'Ultra Fast Reflex Reaction Arcade',
    tagline: 'Tap rapid glowing targets, dodge treacherous hazard decoys, and chain rush combos across escalating levels!',
    description: 'An adrenaline-fueled reflex reaction arcade experience engineered for tournament gaming. Tap shrinking target spheres with lightning-fast hand-eye coordination, evade dangerous red hazard decoys, rack up streak multipliers in Rush Mode, and survive through escalating level speeds to claim the top high score.',
    thumbnail: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&auto=format&fit=crop&q=80',
    accessType: 'FREE',
    isFree: true,
    requiresCoins: false,
    coinCost: 0,
    isFeatured: true,
    isRecommended: true,
    isNew: true,
    isActive: true,
    leaderboardEnabled: true,
    sortOrder: 34,
    providerId: 'prv_gameon_core',
    providerName: 'GameON Studios',
    rating: 4.96,
    playsCount: 165000,
    primaryColor: '#06B6D4',
    secondaryColor: '#3B82F6',
    instructions: [
      'Rapidly tap the glowing target spheres before their outer countdown ring shrinks to the center',
      'Never tap red hazard decoys or skulls — detonating a decoy costs 1 life instantly',
      'Do not let valid targets expire and vanish, or you will lose a heart and reset your combo streak',
      'Chain rapid taps without mistakes to trigger 2x, 3x, and 4x score multipliers and bonus points',
      'Fill the Level Progress Bar to conquer stages and survive into ultra-speed reflex levels',
    ],
    controlsDescription: 'Tap or click glowing targets before they vanish. Avoid red hazard decoys. 100% mobile touch and desktop mouse responsive.',
  }
];

export const GameCatalog = {
  getAll(): CatalogGame[] {
    const orderIndexMap = new Map(MANDATORY_CATALOG_ORDER.map((id, idx) => [id, idx]));
    return INITIAL_GAME_CATALOG.filter((g) => g.isActive && orderIndexMap.has(g.gameId as any))
      .sort((a, b) => (orderIndexMap.get(a.gameId as any) ?? 999) - (orderIndexMap.get(b.gameId as any) ?? 999))
      .map((g) => {
        const art = getGameArtworkUrl(g.gameId);
        return art ? { ...g, thumbnail: art, banner: art } : g;
      });
  },

  getById(gameId: string): CatalogGame | undefined {
    const g = INITIAL_GAME_CATALOG.find((g) => g.gameId === gameId);
    if (!g) return undefined;
    const art = getGameArtworkUrl(g.gameId);
    return art ? { ...g, thumbnail: art, banner: art } : g;
  },

  getByCategory(category: string): CatalogGame[] {
    if (category === 'All Games') {
      return this.getAll();
    }
    return this.getAll().filter((g) => g.category.toLowerCase() === category.toLowerCase());
  },

  /**
   * Only return categories that currently contain active games, with 'All Games' first
   */
  getCategoriesWithGames(): string[] {
    const categoriesSet = new Set<string>();
    this.getAll().forEach((game) => {
      categoriesSet.add(game.category);
    });

    // Ensure order conforms to ALL_STANDARD_CATEGORIES
    const ordered = ALL_STANDARD_CATEGORIES.filter(
      (cat) => cat === 'All Games' || categoriesSet.has(cat)
    );
    return ordered as unknown as string[];
  },

  getFeatured(): CatalogGame[] {
    return this.getAll().filter((g) => g.isFeatured);
  },

  getRecommended(): CatalogGame[] {
    return this.getAll().filter((g) => g.isRecommended);
  },

  getRecentlyPlayed(ids: string[]): CatalogGame[] {
    if (!ids || ids.length === 0) return [];
    return ids
      .map((id) => this.getById(id))
      .filter((g): g is CatalogGame => Boolean(g));
  },

  search(query: string): CatalogGame[] {
    if (!query.trim()) return this.getAll();
    const q = query.toLowerCase().trim();
    return this.getAll().filter(
      (g) =>
        g.gameName.toLowerCase().includes(q) ||
        g.titleAmharic.includes(query) ||
        g.category.toLowerCase().includes(q) ||
        g.tagline.toLowerCase().includes(q) ||
        g.genre.toLowerCase().includes(q)
    );
  },
};
